# Content package for SIH 26155 Master Report
# Each part module exports a get_html() function returning HTML content

from content.part1 import get_html as get_part1
from content.part2 import get_html as get_part2
from content.part3 import get_html as get_part3


def get_all_content():
    """Return the complete merged HTML content for the report."""
    return get_part1() + get_part2() + get_part3()


def get_toc_entries():
    """Return list of (id, title, level) for table of contents."""
    return [
        # Part 1 — Sections 1-13
        ("exec-summary", "Executive Summary", 1),
        ("official-problem", "1. Official Problem Statement (SIH26-26155)", 1),
        ("problem-simple", "1.1 In Simple Language", 2),
        ("problem-technical", "1.2 Technical Explanation", 2),
        ("what-ntro-wants", "1.3 What NTRO Actually Wants", 2),
        ("why-matters", "2. Why This Problem Matters", 1),
        ("real-world-impact", "2.1 Real-World Impact", 2),
        ("real-world-examples", "2.2 Real-World Compliance Examples", 2),
        ("current-situation", "3. Current Industry Situation", 1),
        ("manual-process", "3.1 Manual Audit Process", 2),
        ("challenges-table", "3.2 Why Manual Audits Fail", 2),
        ("existing-solutions", "4. Existing Solutions & Competitor Analysis", 1),
        ("competitor-products", "4.1 Existing Products", 2),
        ("competitor-matrix", "4.2 Feature Comparison Matrix", 2),
        ("gaps", "4.3 Gaps in Existing Solutions", 2),
        ("compliance-standards", "5. Compliance Standards Deep-Dive", 1),
        ("cis-benchmarks", "5.1 CIS Benchmarks", 2),
        ("nist-800-53", "5.2 NIST SP 800-53", 2),
        ("nist-csf", "5.3 NIST Cybersecurity Framework (CSF)", 2),
        ("disa-stigs", "5.4 DISA STIGs", 2),
        ("iso-27001", "5.5 ISO/IEC 27001", 2),
        ("rfcs", "5.6 Relevant RFCs", 2),
        ("vendor-guides", "5.7 Vendor Security Hardening Guides", 2),
        ("compliance-mapping", "5.8 Cross-Framework Compliance Mapping", 2),
        ("vendor-configs", "6. Vendor-Specific Network Configurations", 1),
        ("cisco-config", "6.1 Cisco IOS / IOS-XE", 2),
        ("juniper-config", "6.2 Juniper Junos", 2),
        ("fortinet-config", "6.3 Fortinet FortiOS", 2),
        ("paloalto-config", "6.4 Palo Alto PAN-OS", 2),
        ("arista-config", "6.5 Arista EOS", 2),
        ("normalization-strategy", "6.6 Configuration Normalization Strategy", 2),
        ("proposed-solution", "7. Proposed NEXUS Solution", 1),
        ("core-idea", "7.1 Core Idea — Vendor-Neutral Security Interpretation", 2),
        ("what-makes-different", "7.2 What Makes NEXUS Different", 2),
        ("core-features", "7.3 Core Features", 2),
        ("advanced-features", "7.4 Advanced Features & Prioritization", 2),

        # Part 2 — Sections 14-26
        ("architecture", "8. System Architecture", 1),
        ("arch-overview", "8.1 Architecture Overview", 2),
        ("mvp-arch", "8.2 36-Hour MVP Architecture", 2),
        ("strong-arch", "8.3 Strong SIH Submission Architecture", 2),
        ("production-arch", "8.4 Production-Grade Future Architecture", 2),
        ("parsing", "9. Configuration Parsing Engine", 1),
        ("parser-comparison", "9.1 Parser Comparison", 2),
        ("ciscoconfparse", "9.2 CiscoConfParse2 — Recommended Parser", 2),
        ("parser-examples", "9.3 Parser Code Examples", 2),
        ("normalization", "10. Configuration Normalization Engine", 1),
        ("why-normalize", "10.1 Why Normalization Is Critical", 2),
        ("openconfig", "10.2 OpenConfig / YANG Approach", 2),
        ("custom-schema", "10.3 Lightweight Custom Schema (Recommended)", 2),
        ("norm-code", "10.4 Normalization Logic (Python)", 2),
        ("compliance-engine", "11. Compliance Engine", 1),
        ("rule-engine", "11.1 Rule Engine Design", 2),
        ("yaml-rules", "11.2 YAML Rule Format", 2),
        ("engine-implementation", "11.3 Engine Implementation (Python)", 2),
        ("example-rules", "11.4 Example Rule Set", 2),
        ("oscal", "11.5 NIST OSCAL Integration", 2),
        ("ai-ml-role", "12. AI/ML Role — Where AI Helps and Where It Doesn't", 1),
        ("ai-suitable", "12.1 AI Suitability Matrix", 2),
        ("ai-architecture", "12.2 Recommended AI Architecture", 2),
        ("ai-explanation", "12.3 AI Explanation Generation", 2),
        ("ai-remediation", "12.4 AI Remediation Generation", 2),
        ("ai-qa", "12.5 Natural Language Q&A", 2),
        ("rag-system", "13. RAG System", 1),
        ("rag-sources", "13.1 Knowledge Sources", 2),
        ("rag-architecture", "13.2 RAG Architecture", 2),
        ("vector-db", "13.3 Vector Database Comparison", 2),
        ("hallucination", "13.4 Hallucination Prevention", 2),
        ("rag-prompt", "13.5 RAG Prompt Template", 2),
        ("remediation-engine", "14. Remediation Engine", 1),
        ("remediation-workflow", "14.1 Remediation Workflow", 2),
        ("remediation-safety", "14.2 Safety Mechanisms", 2),
        ("risk-scoring", "15. Risk Scoring", 1),
        ("scoring-model", "15.1 Scoring Model", 2),
        ("risk-formula", "15.2 CVSS-Inspired Risk Score", 2),
        ("risk-implementation", "15.3 Implementation", 2),
        ("adaptive-learning", "16. Adaptive Learning — Signature Feature", 1),
        ("adaptive-concept", "16.1 The Adaptive Learning Concept", 2),
        ("adaptive-ui", "16.2 Training Center UI", 2),
        ("knowledge-store", "16.3 Configuration Knowledge Base", 2),
        ("confidence-model", "16.4 Confidence Model", 2),
        ("config-drift", "17. Configuration Drift Detection", 1),
        ("drift-problem", "17.1 The Drift Problem", 2),
        ("drift-implementation", "17.2 Implementation", 2),
        ("security-arch", "18. Security Architecture", 1),
        ("threats", "18.1 Threats Against Our System", 2),
        ("secret-redaction", "18.2 Secret Redaction", 2),
        ("llm-privacy", "18.3 LLM Privacy Architecture", 2),
        ("ai-safety", "18.4 AI Safety Guardrail Layer", 2),

        # Part 3 — Sections 27-39
        ("dataset-strategy", "19. Dataset Strategy", 1),
        ("dataset-requirements", "19.1 Dataset Requirements & Sources", 2),
        ("dataset-layers", "19.2 Dataset Layers", 2),
        ("synthetic-generation", "19.3 Synthetic Config Generation", 2),
        ("dataset-schema", "19.4 Dataset Schema", 2),
        ("ground-truth", "20. Ground Truth & Evaluation", 1),
        ("why-ground-truth", "20.1 Why Ground Truth Matters", 2),
        ("eval-metrics", "20.2 Evaluation Metrics", 2),
        ("presenting-metrics", "20.3 Presenting Metrics at SIH", 2),
        ("tech-stack", "21. Technology Stack", 1),
        ("stack-comparison", "21.1 Component Comparison", 2),
        ("recommended-stack", "21.2 Final Recommended Stack", 2),
        ("ui-ux", "22. UI/UX Concept", 1),
        ("user-flow", "22.1 Complete User Flow", 2),
        ("dashboard-pages", "22.2 Dashboard Pages", 2),
        ("feasibility", "23. Feasibility & Technical Challenges", 1),
        ("challenges", "23.1 Technical Challenges", 2),
        ("failure-modes", "23.2 Failure Modes & Risk Matrix", 2),
        ("limitations", "23.3 Limitations", 2),
        ("innovation", "24. Innovation & Novelty", 1),
        ("differentiators", "24.1 Key Differentiators", 2),
        ("strongest-claims", "24.2 Strongest Innovation Claims", 2),
        ("sih-differentiation", "24.3 SIH Differentiation", 2),
        ("scalability", "25. Scalability & Deployment", 1),
        ("deployment-options", "25.1 Deployment Options", 2),
        ("air-gapped", "25.2 Air-Gapped Deployment", 2),
        ("what-not-to-build", "26. What NOT to Build", 1),
        ("cut-list", "26.1 Features to Cut for 36 Hours", 2),
        ("focus-core", "26.2 Focus on Core", 2),
        ("implementation-plan", "27. 36-Hour Hackathon Implementation Plan", 1),
        ("pre-hackathon", "27.1 Pre-Hackathon Preparation", 2),
        ("phases", "27.2 Implementation Phases", 2),
        ("team-roles", "27.3 Team Role Distribution", 2),
        ("demo-strategy", "28. Demo Strategy", 1),
        ("demo-script", "28.1 3–5 Minute Demo Script", 2),
        ("wow-moments", "28.2 Top 5 Wow Moments", 2),
        ("presentation", "29. SIH Presentation Strategy", 1),
        ("five-slides", "29.1 5-Slide Technical Presentation", 2),
        ("pitch-strategy", "29.2 How to Pitch 26155", 2),
        ("judging-strategy", "29.3 Judging Strategy", 2),
        ("judge-qa", "30. Judge Questions & Answers", 1),
        ("testing-strategy", "31. Testing Strategy", 1),
        ("future-roadmap", "32. Future Roadmap", 1),
        ("final-verdict", "33. Final Verdict & Scores", 1),
        ("references", "34. References", 1),
        ("appendix-a", "Appendix A: Configuration Examples", 1),
        ("appendix-b", "Appendix B: Compliance Rule YAML", 1),
        ("appendix-c", "Appendix C: Normalization Schema", 1),
    ]
