set deviceconfig system hostname PA-FW-NOBAN
set deviceconfig system service disable-telnet yes
set deviceconfig system service disable-http yes
set deviceconfig system idle-timeout 10
set deviceconfig system ntp-servers primary-ntp-server ntp-server-address 10.1.1.50
set shared log-settings syslog Syslog-Server server Syslog-Host server 10.1.1.100
set network interface ethernet ethernet1/1 layer3 ip 172.16.1.1/24
set rulebase security rules BLOCK-ALL from UNTRUST to TRUST source any destination any action deny
