system {
    host-name JUNIPER-FW-02;
    services {
        ssh {
            protocol-version v2;
        }
        
    }
    login {
        class admin-class {
            idle-timeout 10;
        }
    }
    syslog {
        host 10.1.1.100 {
            any informational;
        }
    }
    ntp {
        server 10.1.1.50;
    }
}
snmp {
    community DiffComm {
        authorization read-only;
    }
}
