system {
    host-name JUNIPER-FW-07;
    services {
        ssh {
            protocol-version v2;
        }
        
    }
    login {
        class admin-class {
            idle-timeout 10;
        }
    }
    
    ntp {
        server 10.1.1.50;
    }
}
snmp {
    community MyC0mmun1ty {
        authorization read-only;
    }
}
