system {
    host-name JUNIPER-FW-08;
    services {
        ssh {
            protocol-version v1;
        }
        
    }
    login {
        class admin-class {
        }
    }
    syslog {
        host 10.1.1.100 {
            any informational;
        }
    }
    
}
snmp {
    community public {
        authorization read-only;
    }
}
