system {
    host-name JUNIPER-FW-04;
    services {
        
        telnet {
        }
    }
    login {
        class admin-class {
            idle-timeout 10;
        }
    }
    syslog {
        host 10.1.1.100 {
            any informational;
        }
    }
    ntp {
        server 10.1.1.50;
    }
}
snmp {
    community MyC0mmun1ty {
        authorization read-only;
    }
}
