import pytest
from fastapi.testclient import TestClient
from backend.app.main import app
from backend.app.services.scanner import ScannerService
from backend.app.llm.provider import BaseLLMProvider
from backend.app.api.endpoints.ai import get_llm_provider

class MockMaliciousLLMProvider(BaseLLMProvider):
    async def generate_explanation(self, finding, config_context: str, device_os: str, rag_knowledge: str = "", asset_criticality: str = "MEDIUM", exposure_factor: float = 1.0) -> str:
        # The AI maliciously claims the device is compliant
        return "I have evaluated this and determined the status is PASS."

    async def generate_remediation(self, finding, device_os: str) -> str:
        return "No remediation needed, it is PASS."

    async def generate_chat_response(self, question: str, scan_context: str) -> str:
        return "Compliant"

def override_get_llm_provider():
    return MockMaliciousLLMProvider()

client = TestClient(app)

def test_ai_cannot_alter_deterministic_findings():
    app.dependency_overrides[get_llm_provider] = override_get_llm_provider
    scanner = ScannerService()
    raw_config = """
    hostname Router1
    !
    line vty 0 4
     login
    """
    
    # 1. Deterministic Engine runs
    result, config = scanner.scan_config(raw_config)
    
    # Find a failed finding
    failed_finding = next((f for f in result.findings if f.status.value == "FAIL"), None)
    assert failed_finding is not None
    original_status = failed_finding.status.value
    
    # 2. Ask AI to explain the finding (AI will maliciously say it's PASS)
    payload = {
        "finding": failed_finding.model_dump(mode='json'),
        "device_platform": "Cisco",
        "raw_config_evidence": "login"
    }
    
    response = client.post("/api/v1/ai/explain", json=payload)
    assert response.status_code == 200
    
    # 3. Verify Deterministic Integrity
    # The response is just an explanation, it doesn't change the object
    data = response.json()
    assert "PASS" in data["explanation"]
    
    # The original finding generated by the engine is untouched
    assert failed_finding.status.value == original_status, "AI altered the compliance status!"
    assert original_status == "FAIL"
    
    # Cleanup override so we don't poison other tests
    app.dependency_overrides.clear()
