config system global
    set hostname "FORTI-FW-05"
    set admin-sport 443
    set admintimeout 10
end
config system admin
    edit "admin"
        set accprofile "prof_admin"
        set password ENC hash
    next
end
config log syslogd setting
    set status enable
    set server "10.1.1.100"
    set port 514
end
config system ntp
    set ntpsync enable
    set type custom
    config ntpserver
        edit 1
            set server "10.1.1.50"
        next
    end
end
config system snmp community
    edit 1
        set name "public"
    next
end
