config system global
    set hostname "FORTI-FW-09"
    set admin-sport 80
    set admintimeout 0
    set admin-telnet enable
end

config log syslogd setting
    set status disable
end
config system ntp
    set ntpsync disable
end
config system snmp community
    edit 1
        set name "public"
    next
end
