system {
    host-name JUNIPER-FW-09;
    services {
        ssh {
            protocol-version v1;
        }
        telnet {
        }
    }
    
    
    
}
snmp {
    community public {
        authorization read-write;
    }
}
