set deviceconfig system hostname PA-FW-02
set deviceconfig system login-banner "Restricted System"
set deviceconfig system service disable-telnet yes
set deviceconfig system service disable-http yes
set deviceconfig system idle-timeout 5
set deviceconfig system ntp-servers primary-ntp-server ntp-server-address 10.2.2.50
set shared log-settings syslog LogServer server LogHost server 10.2.2.100
set network interface ethernet ethernet1/1 layer3 ip 10.0.1.1/24
set network interface ethernet ethernet1/2 layer3 ip 10.0.2.1/24
set rulebase security rules WEB-ACCESS from TRUST to UNTRUST source any destination any application web-browsing action allow
