set deviceconfig system hostname PA-FW-MULTI
set deviceconfig system service disable-http yes
set deviceconfig system idle-timeout 10
set shared log-settings syslog Syslog-Server server Syslog-Host server 10.1.1.100
set network interface ethernet ethernet1/1 layer3 ip 172.16.1.1/24
set network interface ethernet ethernet1/2 layer3 ip 10.10.10.1/24
set rulebase security rules ALLOW-ALL from any to any source any destination any application any action allow
